site_name: UltraSuite Repository
site_description: A repository of ultrasound and acoustic data from child speech therapy sessions

theme:
  name: readthedocs
  custom_dir: custom/
  logo_only: False
  collapse_navigation: False

use_directory_urls: True

extra_css:
    - extra.css

nav:
    - Home: index.md
    - Ultrax Typically Developing: data/uxtd.md
    - Ultrax Speech Sound Disorders: data/uxssd.md
    - Ultraphonix: data/upx.md
    - TaL Corpus: data/tal_corpus.md
    - Community: community.md
    - Download: download.md
    - Frequently Asked Questions: faq.md
